import "./fonts/Lato/lato.css";
import "../node_modules/source-sans-pro/source-sans-pro.css";
import "../node_modules/font-awesome/css/font-awesome.min.css";

import "jquery";
import "jquery-validation";
import "chart.js";
import "../scripts/jquery-ui-1.12.1.custom/jquery-ui.min.js";
import "../scripts/jquery-ui-1.12.1.custom/jquery-ui.min.css";
import "../node_modules/jquery-ui-slider-pips/dist/jquery-ui-slider-pips.min.js"
import "../node_modules/jquery-ui-slider-pips/dist/jquery-ui-slider-pips.min.css"
import "../node_modules/css-ripple-effect/dist/ripple.min.css";
import "jquery-circle-progress";
import "../node_modules/jquery-steps/build/jquery.steps.min.js";
import "../node_modules/select2/dist/js/select2.min.js";
import "../node_modules/select2/dist/css/select2.min.css";
import "maplace-js";

import "./blocks/main-container/main-container.styl";
import "./blocks/standard-buttons-container/standard-buttons-container.styl";
import "./blocks/standard-button/standard-button.styl";
import "./blocks/arrow-buttons-container/arrow-buttons-container.styl";
import "./blocks/arrow-buttons-container/arrow-buttons-container.js";
import "./blocks/arrow-button/arrow-button.styl";
import "./blocks/percentages-pie-chart-container/percentages-pie-chart-container.styl";
import "./blocks/percentage/percentage.styl";
import "./blocks/percentage/percentage.js";
import "./blocks/pie-chart/pie-chart.js";
import "./blocks/pie-chart/pie-chart.styl";
import "./blocks/sliders-container/sliders-container.styl";
import "./blocks/slider/slider.styl";
import "./blocks/slider/slider.js";
import "./blocks/stages-container/stages-container.styl";
import "./blocks/stages/stages.styl";
import "./blocks/stages/stages.js";
import "./blocks/toggles-container/toggles-container.styl";
import "./blocks/toggle/toggle.styl";
import "./blocks/toggle/toggle.js";
import "./blocks/tick-box-container/tick-box-container.styl";
import "./blocks/tick-box/tick-box.styl";
import "./blocks/tick-box/tick-box.js";
import "./blocks/form-elements-container/form-elements-container.styl";
import "./blocks/send-message/send-message.styl";
import "./blocks/send-message/send-message.js";
import "./blocks/search-dropdown-container/search-dropdown-container.js";
import "./blocks/search-dropdown-container/search-dropdown-container.styl";
import "./blocks/search/search.styl";
import "./blocks/dropdown/dropdown.styl";
import "./blocks/dropdown/dropdown.js";
import "./blocks/user-profile-container/user-profile-container.styl";
import "./blocks/user-profile/user-profile.styl";
import "./blocks/user-profile/img/man.png";
import "./blocks/user-profile/img/woman.png";
import "./blocks/news-events-container/news-events-container.styl";
import "./blocks/news/news.styl";
import "./blocks/event/event.styl";
//import "./blocks/location-container/location-container.styl";
//import "./blocks/calendar-container/calendar-container.styl";
//import "./blocks/messaging-container/messaging-container.styl";
//import "./blocks/video-container/video-container.styl";


